#!/usr/bin/env bash
# This script displays "Best School" 9 times and the las t line hi using while

a=1
while [ $a -lt 10 ]
do 
	echo "Best school"
	((a++))
done
n=9
while [ $n -lt 10 ]
do
	echo "hi"
	((n++))
done
